/*
 *	DRAW MANHATTAN and QQ PLOTs
 *	===========================
 *
 *	This script runs an initial association test for your input data.
 *	Specifically, it draws manhattan and QQ plots for the raw
 *	unfiltered cohort data. 
 *
 *	The cohort data is:
 *		+ <cohort name>.bed
 *		+ <cohort name>.bim
 *		+ <cohort name>.fam
 *
 *	The association report is generated by a call to plink. 
 *
 ********************************************************************/
nextflow.enable.dsl=2

include {
    checkInputParams;
	getInputChannels;
	getAssociationReport;
	drawManhattanPlot;
	drawQqPlot;
	sendWorkflowExitEmail;
} from "${projectDir}/modules/manhattanQq.nf"

include {
    printWorkflowExitMessage;
} from "${projectDir}/modules/intensityPlot.nf"

workflow {

    checkInputParams()

	cohortData = getInputChannels()

	associationReport = getAssociationReport(cohortData.collect())

	drawManhattanPlot(associationReport)

	drawQqPlot(associationReport)

}

workflow.onComplete {
    printWorkflowExitMessage()
    sendWorkflowExitEmail()
}